In [1]:
import pandas as pd

file_path = "nike_products_with_features.csv"
df = pd.read_csv(file_path)

# Create a binary label column based on 'Badge'
df['Label'] = df['Badge'].apply(lambda x: 1 if 'Best Seller' in str(x) else 0)

# Save the labeled dataset
labelled_file_path = "nike_labelled_data.csv"
df.to_csv(labelled_file_path, index=False)

# Display confirmation
print(f"Labeled data saved as {labelled_file_path}")
df.head()

Labeled data saved as nike_labelled_data.csv

,Title,Subtitle,Price,Initial Price,Discount (%),Color,Color Description,Badge,Discount Amount,Discount Flag,...,Color_Purple,Color_Red,Color_White,Color_Yellow,Dominant Color,Title Word Count,Subtitle Word Count,Marketing Appeal Score,Sale Quantity,Label
0,Nike C1TY,Shoes,100.0,100,0,Pink,Red Stardust/Canyon Rust/Burgundy Crush/Black,Just In,0.0,0,...,False,False,False,False,Red Stardust,2,1,8,69,0
1,Nike C1TY,Shoes,100.0,100,0,Grey,Smoke Grey/Medium Ash/Aquarius Blue/Summit White,Just In,0.0,0,...,False,False,False,False,Smoke Grey,2,1,9,810,0
2,Nike C1TY,Men's Shoes,100.0,100,0,Orange,Safety Orange/Cosmic Clay/Black/Summit White,Just In,0.0,0,...,False,False,False,False,Safety Orange,2,2,10,421,0
3,Nike C1TY,Shoes,100.0,100,0,Brown,Desert Khaki/Parachute Beige/University Gold/B...,Just In,0.0,0,...,False,False,False,False,Desert Khaki,2,1,9,61,0
4,Nike C1TY,Shoes,100.0,100,0,Brown,Soft Pearl/Light Khaki/Lightning/Black,NaN,0.0,0,...,False,False,False,False,Soft Pearl,2,1,4,995,0